export default {
  footer:  "footer" ,
footer_link:"footer-link",
footer_image:"footer-image",
header:"header" ,
home_button:"home-button",
about_button:"about-button",
contact_button:"contact-button",
select_language_button:"select-language-button",
button_moon_sun:"button-moon-sun" ,
not_found:"not-found" ,
about:"about" ,
about_myself:"about-myself",
about_picture:"about-picture",
contact:"contact" ,
contact_icon_linkedin:"contact-icon-linkedin",
contact_icon_instagram:"contact-icon-instagram",
contact_icon_youtube:"contact-icon-youtube",
home:"home" ,
profile_picture_container:"profile-picture-container",
introduction:"introduction" ,
introduction_text:"introduction-text" ,
section_display_container_container:"section-display-container-container",
all_projects_display:"all-projects-display",
project_display_container_1:"project-display-container-1",
project_display_image_1:"project-display-image-1",
project_display_button_deploy_link_1:"project-display-button-deploy-link-1",
project_display_button_deploy_1:"project-display-button-deploy-1",
project_display_button_github_link_1:"project-display-button-github-link-1",
project_display_button_github_1:"project-display-button-github-1",
project_display_container_2:"project-display-container-2",
project_display_image_2:"project-display-image-2",
project_display_button_deploy_link_2:"project-display-button-deploy-link-2",
project_display_button_deploy_2:"project-display-button-deploy-2",
project_display_button_github_link_2:"project-display-button-github-link-2",
project_display_button_github_2:"project-display-button-github-2",
}
